name: Tauri Cross-Platform Build

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - Windows
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      TAURI_SKIP_UPDATE_CHECK: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: autohotpie-tauri/package-lock.json

      - name: Setup Rust
        shell: powershell
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup component add clippy rustfmt
          rustup target add ${{ matrix.target }}

      - name: Install frontend deps
        working-directory: autohotpie-tauri
        run: npm install

      - name: Build UI
        working-directory: autohotpie-tauri
        run: npm run build

      - name: Build Tauri bundle
        working-directory: autohotpie-tauri
        run: npm run tauri build -- --target ${{ matrix.target }}

      - name: Smoke test bundle
        if: matrix.os != 'macos-14'
        working-directory: autohotpie-tauri
        run: |
          npx tauri info
          npm run tauri build -- --target ${{ matrix.target }} --ci

      - name: Upload artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.os }}
          path: |
            autohotpie-tauri/src-tauri/target/**/*.msi
            autohotpie-tauri/src-tauri/target/**/*.exe
            autohotpie-tauri/src-tauri/target/**/*.dmg
            autohotpie-tauri/src-tauri/target/**/*.appimage
            autohotpie-tauri/src-tauri/target/**/*.deb
            autohotpie-tauri/src-tauri/target/**/*.rpm