name: Tauri Cross-Platform Build

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      TAURI_SKIP_UPDATE_CHECK: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: autohotpie-tauri/package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
          targets: ${{ matrix.target }}

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev webkit2gtk-4.1 libssl-dev

      - name: Install dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew tap gcenx/homebrew-webkitgtk || true
          brew install gcenx/homebrew-webkitgtk/webkitgtk-4.1 || brew install gcenx/homebrew-webkitgtk/webkitgtk || true

      - name: Install frontend deps
        working-directory: autohotpie-tauri
        run: npm install

      - name: Build UI
        working-directory: autohotpie-tauri
        run: npm run build

      - name: Build Tauri bundle
        working-directory: autohotpie-tauri
        run: npm run tauri build -- --target ${{ matrix.target }}

      - name: Smoke test bundle
        if: matrix.os != 'macos-14'
        working-directory: autohotpie-tauri
        run: |
          npx tauri info
          npm run tauri build -- --target ${{ matrix.target }} --ci

      - name: Upload artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.os }}
          path: |
            autohotpie-tauri/src-tauri/target/**/*.msi
            autohotpie-tauri/src-tauri/target/**/*.exe
            autohotpie-tauri/src-tauri/target/**/*.dmg
            autohotpie-tauri/src-tauri/target/**/*.appimage
            autohotpie-tauri/src-tauri/target/**/*.deb
            autohotpie-tauri/src-tauri/target/**/*.rpm